remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
title: >
  Jonathan Bar Or ("JBO")
description: >
  Jonathan Bar Or ("JBO") is an information security expert and a hacker
  focusing on binary analysis, vulnerability research, application security,
  reverse engineering and cryptography
show_downloads: false
github:
  is_project_page: false
