theme: Hacker
plugins:
- jekyll-remote-theme
title: "Jonathan Bar Or"
description: >
  Jonathan Bar Or ("JBO") is an information security expert and a hacker
  focusing on binary analysis, vulnerability research, application security,
  reverse engineering and cryptography
